### ISSUE TITLE
missing chalk dependency

### ISSUE THREAD

**Issue by 1wheel** [Rich-Harris/buble#35]
```
➜  2017-11-07-tax-table git:(master) ✗ yarn add buble
➜  2017-11-07-tax-table git:(master) ✗ node_modules/.bin/buble public/_assets/build-es6.js
module.js:529
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/207342/Desktop/2017-11-07-tax-table/node_modules/buble/bin/handleError.js:1:75)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
➜  2017-11-07-tax-table git:(master) ✗ yarn add chalk
➜  2017-11-07-tax-table git:(master) ✗ node_modules/.bin/buble public/_assets/build-es6.js
// works now
```

This is with version `0.17.0`. 

It looks like `chalk` is currently in `devDependencies`; not sure if it being called inadvertently or if it should be in `dependencies` .

**Comment by Rich-Harris** [comment]
fixed in 0.17.3, thanks
