### ISSUE TITLE
BUG: Cannot read property 'ref_B' of null

### ISSUE THREAD

**Issue by kgdev** [Rich-Harris/buble#98]
```
function A() {
	if (1) {
		const {
			B: {C, D},
		} = {};
	}
}

```

**Comment by kgdev** [comment]
```
buble test.js
Cannot read property 'ref_B' of null
TypeError: Cannot read property 'ref_B' of null
    at Scope.createIdentifier (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:13537:16)
    at handleProperty (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:7386:17)
    at node.properties.forEach.prop (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:7301:3)
    at Array.forEach (<anonymous>)
    at Object.destructureObjectPattern [as ObjectPattern] (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:7270:18)
    at destructure (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:7174:21)
    at declarations.forEach (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:13271:6)
    at Array.forEach (<anonymous>)
    at Node.transpile (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:13234:22)
    at value.forEach.node (/Users/kg/.config/yarn/global/node_modules/buble/dist/buble.deps.js:5752:40)
```

**Comment by kgdev** [comment]
in createIdentifier **this.aliases** could be null?

**Comment by adrianheine** [comment]
Thanks for reporting, but I cannot reproduce this with current master. I'll try to make a release soon.
